; ============================================================================
; Inno Setup Script for DERSIS — Class Scheduling System
;
; Works with both build methods:
;   - Nuitka standalone:    build_nuitka.bat → iscc installer.iss
;   - Embeddable Python:    build_embed.bat  → iscc installer.iss
;
; Both produce output in build\Dersis.dist\
;
; Prerequisites:
;   1. Run build_embed.bat (recommended) or build_nuitka.bat
;   2. Install Inno Setup 6.x from https://jrsoftware.org/isinfo.php
;   3. Compile: iscc installer.iss
;
; Output: Output\Dersis_Setup.exe
; ============================================================================

; ── Minimum Inno Setup version ──────────────────────────────────────────────
; This script uses the "x64compatible" architecture identifier, which was
; introduced in Inno Setup 6.3.0. Fail early with a clear message on older
; compilers instead of a confusing "invalid [Setup] value" error.
#if VER < EncodeVer(6,3,0)
  #error Inno Setup 6.3.0 or newer is required to compile this script (the x64compatible architecture identifier was added in 6.3.0).
#endif

; Version is generated by build_embed.bat from the VERSION file.
; If build\version.iss does not exist, fall back to a default.
#define AppName        "Dersis"
#define AppFullName    "Dersis - Class Scheduling System"
#ifexist "build\version.iss"
  #include "build\version.iss"
#else
  #define AppVersion   "0.0.0"
#endif
#define AppPublisher   "Uygun"
#define AppCopyright   "Copyright (c) Uygun"
#define AppURL         ""

[Setup]
AppId={{A1B2C3D4-E5F6-7890-ABCD-EF1234567890}
AppName={#AppFullName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
AppPublisher={#AppPublisher}
AppCopyright={#AppCopyright}
DefaultDirName={autopf}\{#AppName}
DefaultGroupName={#AppName}
OutputDir=Output
OutputBaseFilename=Dersis_Setup_v{#AppVersion}
SetupIconFile=scheduler_app\assets\app_icon.ico
UninstallDisplayIcon={app}\scheduler_app\assets\app_icon.ico
UninstallDisplayName={#AppFullName}
LicenseFile=installer\LICENSE.txt
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
WizardSizePercent=110,110
PrivilegesRequired=lowest
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
AllowNoIcons=yes
DisableProgramGroupPage=yes
VersionInfoVersion={#AppVersion}
VersionInfoCompany={#AppPublisher}
VersionInfoDescription={#AppFullName} Setup
VersionInfoCopyright={#AppCopyright}
VersionInfoProductName={#AppName}
VersionInfoProductVersion={#AppVersion}

; Installer branding
WizardImageFile=installer\wizard_image.bmp
WizardSmallImageFile=installer\wizard_small_image.bmp

[Languages]
Name: "english";    MessagesFile: "compiler:Default.isl"
Name: "turkish";    MessagesFile: "compiler:Languages\Turkish.isl"
Name: "german";     MessagesFile: "compiler:Languages\German.isl"
Name: "french";     MessagesFile: "compiler:Languages\French.isl"
Name: "spanish";    MessagesFile: "compiler:Languages\Spanish.isl"
Name: "italian";    MessagesFile: "compiler:Languages\Italian.isl"
Name: "dutch";      MessagesFile: "compiler:Languages\Dutch.isl"
Name: "polish";     MessagesFile: "compiler:Languages\Polish.isl"
Name: "portuguese"; MessagesFile: "compiler:Languages\Portuguese.isl"
Name: "russian";    MessagesFile: "compiler:Languages\Russian.isl"
Name: "japanese";   MessagesFile: "compiler:Languages\Japanese.isl"
Name: "korean";     MessagesFile: "compiler:Languages\Korean.isl"
Name: "danish";     MessagesFile: "compiler:Languages\Danish.isl"

; Note: Arabic, Persian, Hindi, Chinese, Swedish, Indonesian, Azerbaijani,
; Afrikaans are fully supported in the app itself (language selection on
; first run). Only the installer UI is limited to Inno Setup built-in languages.

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Entire build output (works for both Nuitka and embed builds)
Source: "build\Dersis.dist\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

; License agreement (also shown by the installer's license page)
Source: "installer\LICENSE.txt"; DestDir: "{app}"; DestName: "LICENSE.txt"; Flags: ignoreversion

; VC++ Redistributable — required on clean machines for Python/Qt
; Download vc_redist.x64.exe from https://aka.ms/vs/17/release/vc_redist.x64.exe
; and place it in the installer\ folder. If not present, installer skips it.
Source: "installer\vc_redist.x64.exe"; DestDir: "{tmp}"; Flags: ignoreversion deleteafterinstall skipifsourcedoesntexist

[Dirs]
Name: "{app}"; Permissions: users-modify

[Icons]
; Start Menu — use the Dersis icon
Name: "{autoprograms}\{#AppName}"; Filename: "{app}\Dersis.exe"; IconFilename: "{app}\scheduler_app\assets\app_icon.ico"
; Desktop (optional)
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\Dersis.exe"; IconFilename: "{app}\scheduler_app\assets\app_icon.ico"; Tasks: desktopicon

[Run]
; Install VC++ Redistributable silently if the file was included
Filename: "{tmp}\vc_redist.x64.exe"; Parameters: "/install /quiet /norestart"; StatusMsg: "Installing Visual C++ Runtime..."; Flags: waituntilterminated skipifdoesntexist

; Launch app after install
Filename: "{app}\Dersis.exe"; Description: "{cm:LaunchProgram,{#AppName}}"; Flags: nowait postinstall skipifsilent shellexec

[UninstallDelete]
Type: filesandordirs; Name: "{app}\__pycache__"
Type: filesandordirs; Name: "{app}\scheduler_app\__pycache__"
Type: filesandordirs; Name: "{app}\scheduler_app\core\__pycache__"
Type: filesandordirs; Name: "{app}\scheduler_app\ui\__pycache__"
Type: filesandordirs; Name: "{app}\scheduler_app\storage\__pycache__"
Type: filesandordirs; Name: "{app}\scheduler_app\learning\__pycache__"
Type: filesandordirs; Name: "{app}\scheduler_app\data_io\__pycache__"
