; ============================================================================
; Inno Setup Script for DERSIS — Class Scheduling System
;
; Works with both build methods:
;   - Nuitka standalone:    build_nuitka.bat → iscc installer.iss
;   - Embeddable Python:    build_embed.bat  → iscc installer.iss
;
; Both produce output in build\Dersis.dist\
;
; Prerequisites:
;   1. Run build_embed.bat (recommended) or build_nuitka.bat
;   2. Install Inno Setup 6.x from https://jrsoftware.org/isinfo.php
;   3. Compile: iscc installer.iss
;
; Output: Output\Dersis_Setup.exe
; ============================================================================

; ── Minimum Inno Setup version ──────────────────────────────────────────────
; This script uses the "x64compatible" architecture identifier, which was
; introduced in Inno Setup 6.3.0. Fail early with a clear message on older
; compilers instead of a confusing "invalid [Setup] value" error.
#if VER < EncodeVer(6,3,0)
  #error Inno Setup 6.3.0 or newer is required to compile this script (the x64compatible architecture identifier was added in 6.3.0).
#endif

; Version is generated by build_embed.bat from the VERSION file.
; If build\version.iss does not exist, fall back to a default.
#define AppName        "Dersis"
#define AppFullName    "Dersis - Class Scheduling System"
#ifexist "build\version.iss"
  #include "build\version.iss"
#else
  #define AppVersion   "0.0.0"
#endif
#define AppPublisher   "Uygun"
#define AppCopyright   "Copyright (c) Uygun"
#define AppURL         ""

[Setup]
; ── DO NOT CHANGE THIS APPID (ST-SEC-007) ───────────────────────────────────
; It looks like a placeholder because it is the canonical tutorial GUID, and
; every reviewer's instinct is to replace it. That instinct is the bug.
;
; Inno Setup keys BOTH upgrade detection and uninstall on AppId, and
; Dersis_Setup_v1.0.0.exe carrying this value has 105+ downloads (build.8 and
; build.10, published 2026-06-19). A new GUID makes every one of those installs
; invisible to the next setup: it installs over the same files, leaves two
; Add/Remove Programs entries, and uninstalling either deletes the other's
; files. Colliding with some other product that pasted the same tutorial GUID is
; strictly less bad than orphaning the installed base.
;
; If the collision risk is ever judged unacceptable, the only correct migration
; is a [Code] InitializeSetup that reads the old
; HKCU\...\Uninstall\{A1B2C3D4-...}_is1\UninstallString, runs it with
; /SILENT /SUPPRESSMSGBOXES, and only then proceeds. That is a real feature with
; real failure modes; it is not worth building to fix a cosmetic GUID.
;
; tests/test_packaging_manifest.py::test_the_installer_appid_is_frozen pins it.
AppId={{A1B2C3D4-E5F6-7890-ABCD-EF1234567890}
AppName={#AppFullName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
AppPublisher={#AppPublisher}
AppCopyright={#AppCopyright}
DefaultDirName={autopf}\{#AppName}
DefaultGroupName={#AppName}
OutputDir=Output
OutputBaseFilename=Dersis_Setup_v{#AppVersion}
SetupIconFile=scheduler_app\assets\app_icon.ico
UninstallDisplayIcon={app}\scheduler_app\assets\app_icon.ico
UninstallDisplayName={#AppFullName}
LicenseFile=installer\LICENSE.txt
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
WizardSizePercent=110,110
PrivilegesRequired=lowest
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
AllowNoIcons=yes
DisableProgramGroupPage=yes
VersionInfoVersion={#AppVersion}
VersionInfoCompany={#AppPublisher}
VersionInfoDescription={#AppFullName} Setup
VersionInfoCopyright={#AppCopyright}
VersionInfoProductName={#AppName}
VersionInfoProductVersion={#AppVersion}

; Installer branding
WizardImageFile=installer\wizard_image.bmp
WizardSmallImageFile=installer\wizard_small_image.bmp

[Languages]
Name: "english";    MessagesFile: "compiler:Default.isl"
Name: "turkish";    MessagesFile: "compiler:Languages\Turkish.isl"
Name: "german";     MessagesFile: "compiler:Languages\German.isl"
Name: "french";     MessagesFile: "compiler:Languages\French.isl"
Name: "spanish";    MessagesFile: "compiler:Languages\Spanish.isl"
Name: "italian";    MessagesFile: "compiler:Languages\Italian.isl"
Name: "dutch";      MessagesFile: "compiler:Languages\Dutch.isl"
Name: "polish";     MessagesFile: "compiler:Languages\Polish.isl"
Name: "portuguese"; MessagesFile: "compiler:Languages\Portuguese.isl"
Name: "russian";    MessagesFile: "compiler:Languages\Russian.isl"
Name: "japanese";   MessagesFile: "compiler:Languages\Japanese.isl"
Name: "korean";     MessagesFile: "compiler:Languages\Korean.isl"
Name: "danish";     MessagesFile: "compiler:Languages\Danish.isl"

; Note: Arabic, Persian, Hindi, Chinese, Swedish, Indonesian, Azerbaijani,
; Afrikaans are fully supported in the app itself (language selection on
; first run). Only the installer UI is limited to Inno Setup built-in languages.

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Entire build output (works for both Nuitka and embed builds)
Source: "build\Dersis.dist\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

; License agreement (also shown by the installer's license page)
Source: "installer\LICENSE.txt"; DestDir: "{app}"; DestName: "LICENSE.txt"; Flags: ignoreversion

; VC++ Redistributable — required on clean machines for Python/Qt
; Download vc_redist.x64.exe from https://aka.ms/vs/17/release/vc_redist.x64.exe
; and place it in the installer\ folder. If not present, installer skips it.
Source: "installer\vc_redist.x64.exe"; DestDir: "{tmp}"; Flags: ignoreversion deleteafterinstall skipifsourcedoesntexist

; ── No [Dirs] section, deliberately (ST-SEC-003) ────────────────────────────
; This script used to carry:
;     [Dirs]
;     Name: "{app}"; Permissions: users-modify
; All three candidate justifications for it were measured false.
;   1. "the app writes __pycache__ into {app}" — build_embed.bat compiles
;      scheduler_app with `compileall -b` and then deletes every .py, so the
;      shipped package is sourceless .pyc and nothing is ever cached there.
;   2. "the bundled site-packages needs to be writable" — probed with
;      `icacls /deny (WD,AD)`: import succeeds, rc=0, zero files written.
;      CPython swallows the bytecode-write OSError. A read-only {app} costs
;      recompilation per launch, not failure.
;   3. "scheduler_gui.py needs {app} for its startup log" — it tries
;      ~/Documents/Dersis/logs first and the temp directory third.
; What the grant did do: PrivilegesRequired=lowest means {autopf} always
; resolves to %LOCALAPPDATA%\Programs, whose fresh directories inherit exactly
; SYSTEM, Administrators and the installing user — no BUILTIN\Users. Adding that
; ACE turned a single-user directory into one every local account on a shared
; staffroom or lab machine can modify, with {app}\python\Lib\site-packages
; sitting inside it. If a writable location is ever genuinely needed it must be
; a subdirectory, never {app} itself.

[Icons]
; Start Menu — use the Dersis icon
Name: "{autoprograms}\{#AppName}"; Filename: "{app}\Dersis.exe"; IconFilename: "{app}\scheduler_app\assets\app_icon.ico"
; Desktop (optional)
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\Dersis.exe"; IconFilename: "{app}\scheduler_app\assets\app_icon.ico"; Tasks: desktopicon

[Run]
; Install VC++ Redistributable silently if the file was included
Filename: "{tmp}\vc_redist.x64.exe"; Parameters: "/install /quiet /norestart"; StatusMsg: "Installing Visual C++ Runtime..."; Flags: waituntilterminated skipifdoesntexist

; Launch app after install
Filename: "{app}\Dersis.exe"; Description: "{cm:LaunchProgram,{#AppName}}"; Flags: nowait postinstall skipifsilent shellexec

[UninstallDelete]
; Python writes __pycache__ beside every source file it imports, and the only
; Python sources in the shipped tree are the ~2,639 .py files across ~626
; package directories under {app}\python\Lib\site-packages (the stdlib lives in
; python311.zip, and zipimport never writes bytecode). Those cache files are not
; in Inno's install log, so without this entry the uninstaller cannot remove
; them and every parent directory then fails to delete as non-empty.
;
; This replaces seven scheduler_app\...\__pycache__ entries that could never
; match anything: build_embed.bat deletes every .py under scheduler_app, and a
; Nuitka build emits no .py at all. They read as cleanup and were not.
Type: filesandordirs; Name: "{app}\python"
Type: dirifempty;     Name: "{app}"
